---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: po1-service-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: po1-service-demo
  template:
    metadata:
      labels:
        app: po1-service-demo
    spec:
      containers:
      - name: po1-service-demo
        imagePullPolicy: Always
        image: 236731556556.dkr.ecr.eu-west-1.amazonaws.com/po1/po1-service-demo:latest
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: po1-service-demo
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
