---
apiVersion: v1
kind: Service
metadata:
  name: po1-service-demo
spec:
  type: ClusterIP
  selector:
    app: po1-service-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
